package com.example.demo.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

@Entity
@Data
@Table
public class Book implements Serializable {
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4074001640868434841L;
	@Id
	@GeneratedValue
//	@ApiModelProperty(value="autogenerated id")		// Can be write in data type model in ui for more meaning full for display
	private int bookId;
//	@ApiModelProperty(value="This will be Book Name")		// Can be write in data type model in ui for more meaning full for display
	private String bookName;
//	@ApiModelProperty(value="this is book price")		// Can be write in data type model in ui for more meaning full for display
	private double bookPrice;

}
